### ISSUE TITLE
Update step creation

### ISSUE THREAD

**Issue by mbfisher** [write-track/prolifiko.com#2]
Step creation page needs to work like goal creation:

- Render a different React component based on subscription status
- Prefill deadline for midnight if five day challenge

**Comment by mbfisher** [comment]
Done most of this this morning. Still to do:

* `CreateStep` and `CreateMidnightStep` tests

M

**Comment by dan-j** [comment]
Is it just tests left to write? I can do this whilst your away?

**Comment by mbfisher** [comment]
Tests are done on this I think...

M

**Comment by mbfisher** [comment]
I'm wrong - I mean React tests. These are up for grabs!

M

**Comment by dan-j** [comment]
Not sure how to get these tests to work because they rely on the global `window.DATA.stepNumber`

i.e. in `CreateMidnightStep.js`:
```
    const stepDetails = props =>
        <StepDetails {...props} stepNumber={window.DATA.stepNumber}/>;
```

**Comment by dan-j** [comment]
Written some tests for these 👍
